version: "3.8"
services:
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always
    links:
      - api
    volumes:
      - ./frontend:/frontend

  api:
    container_name: node_assignment
    restart: always
    build: ./backend/
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=postgres_db
      - PG_DB=pccw_db
      - PG_USER=pccw_user
      - PG_PASSWORD=pccw_password
    depends_on:
      - postgres_db
    volumes:
      - ./api:/api

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=pccw_db
      - POSTGRES_USER=pccw_user
      - POSTGRES_PASSWORD=pccw_password

volumes:
  data: {}
